name: Actualizar README con actividad reciente

on:
  schedule:
    - cron: "0 */6 * * *"   # cada 6 h; usa UTC
  workflow_dispatch:          # para que lo lances manualmente si quieres

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jamesgeorge007/github-activity-readme@v0.4.5
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_LINES: 5           # número de eventos a mostrar
